const states = {
  alabama: {
    id :1,
    code: "AL",
    name: "Alabama",
    cities: [],
  },
  alaska: {
    id: 2,
    code: "AK",
    name: "Alaska",
    cities: [],
  },
  arizona: {
    id: 3,
    code: "AZ",
    name: "Arizona",
    cities: [],
  },
  arkansas: {
    id: 4,
    code: "AR",
    name: "Arkansas",
    cities: [],
  },
  california: {
    id: 5,
    code: "CA",
    name: "California",
    cities: ["Los Angeles", "San Diego", "San Francisco", "Rialto",
      "Cerritos", "Santa Monica", "Venice", "Glendale", "Burbank", "Pasadena",
      "Redlands", "Palm Springs", "Oakland", "West Hollywood", "New Port Beach",
      "Malibu", "Anaheim", "Corona"
    ],
    counties: ["San Bernardino", "Los Angeles", "Riverside", "Hollywood",
      "Santa Barbara", "Alameda", "Ventura", "Santa Clara", "Orange", "Kern"
    ]
  },
  colorado: {
    id: 6,
    code: "CO",
    name: "Colorado",
    cities: [],
  },
  connecticut: {
    id: 7,
    code: "CT",
    name: "Connecticut",
    cities: [],
  },
  delaware: {
    id: 8,
    code: "DE",
    name: "Delaware",
    cities: [],
  },
  districtOfColumbia: {
    id: 9,
    code: "DC",
    name: "District Of Columbia",
    cities: [],
  },
  florida: {
    id: 10,
    code: "FL",
    name: "Florida",
    cities: [],
  },
  georgia: {
    id: 11,
    code: "GA",
    name: "Georgia",
    cities: [],
  },
  hawaii: {
    id: 12,
    code: "HI",
    name: "Hawaii",
    cities: [],
  },
  idaho: {
    id: 13,
    code: "ID",
    name: "Idaho",
    cities: [],
  },
  illinois: {
    id: 14,
    code: "IL",
    name: "Illinois",
    cities: [],
  },
  indiana: {
    id: 15,
    code: "IN",
    name: "Indiana",
    cities: [],
  },
  iowa: {
    id: 16,
    code: "IA",
    name: "Iowa",
    cities: [],
  },
  kansas: {
    id: 17,
    code: "KS",
    name: "Kansas",
    cities: [],
  },
  kentucky: {
    id: 18,
    code: "KY",
    name: "Kentucky",
    cities: [],
  },
  louisiana: {
    id: 19,
    code: "LA",
    name: "Louisiana",
    cities: [],
  },
  maine: {
    id: 20,
    code: "ME",
    name: "Maine",
    cities: [],
  },
  maryland: {
    id: 21,
    code: "MD",
    name: "Maryland",
    cities: [],
  },
  massachusetts: {
    id: 22,
    code: "MA",
    name: "Massachusetts",
    cities: [],
  },
  michigan: {
    id: 23,
    code: "MI",
    name: "Michigan",
    cities: [],
  },
  minnesota: {
    id: 24,
    code: "MN",
    name: "Minnesota",
    cities: [],
  },
  mississippi: {
    id: 25,
    code: "MS",
    name: "Mississippi",
    cities: [],
  },
  missouri: {
    id: 26,
    code: "MO",
    name: "Missouri",
    cities: [],
  },
  montana: {
    id: 27,
    code: "MT",
    name: "Montana",
    cities: [],
  },
  nebraska: {
    id: 28,
    code: "NE",
    name: "Nebraska",
    cities: [],
  },
  nevada: {
    id: 29,
    code: "NV",
    name: "Nevada",
    cities: [],
  },
  newHampshire: {
    id: 30,
    code: "NH",
    name: "New Hampshire",
    cities: [],
  },
  newJersey: {
    id: 31,
    code: "NJ",
    name: "New Jersey",
    cities: [],
  },
  newMexico: {
    id: 32,
    code: "NM",
    name: "New Mexico",
    cities: [],
  },
  newYork: {
    id: 33,
    code: "NY",
    name: "New York",
    cities: [],
  },
  northCarolina: {
    id: 34,
    code: "NC",
    name: "North Carolina",
    cities: [],
  },
  northDakota: {
    id: 35,
    code: "ND",
    name: "North Dakota",
    cities: [],
  },
  ohio: {
    id: 36,
    code: "OH",
    name: "Ohio",
    cities: [],
  },
  oklahoma: {
    id: 37,
    code: "OK",
    name: "Oklahoma",
    cities: [],
  },
  oregon: {
    id: 38,
    code: "OR",
    name: "Oregon",
    cities: [],
  },
  pennsylvania: {
    id:39,
    code: "PA",
    name: "Pennsylvania",
    cities: [],
  },
  rhodeIsland: {
    id: 40,
    code: "RI",
    name: "Rhode Island",
    cities: [],
  },
  southCarolina: {
    id: 41,
    code: "SC",
    name: "South Carolina",
    cities: [],
  },
  southDakota: {
    id: 42,
    code: "SD",
    name: "South Dakota",
    cities: [],
  },
  tennessee: {
    id: 43,
    code: "TN",
    name: "Tennessee",
    cities: [],
  },
  texas: {
    id: 44,
    code: "TX",
    name: "Texas",
    cities: [],
  },
  utah: {
    id: 45,
    code: "UT",
    name: "Utah",
    cities: [],
  },
  vermont: {
    id: 46,
    code: "VT",
    name: "Vermont",
    cities: [],
  },
  virginia: {
    id: 47,
    code: "VA",
    name: "Virginia",
    cities: [],
  },
  washington: {
    id: 48,
    code: "WA",
    name: "Washington",
    cities: [],
  },
  westVirginia: {
    id: 49,
    code: "WV",
    name: "West Virginia",
    cities: [],
  },
  wisconsin: {
    id: 50,
    code: "WI",
    name: "Wisconsin",
    cities: [],
  },
  wyoming: {
    id: 51,
    code: "WY",
    name: "Wyoming",
    cities: [],
  }
};

export default states;
