  version: '3'
  services:

    db:
      image: postgres
      ports:
        - "5555:5432"
      volumes:
        - /var/lib/postgresql/data
      restart: always
      networks:
        - roof

    web:
      build: .
      volumes:
        - .:/production
      ports:
        - "3000:3000"
      networks:
        - roof
      restart: always
      depends_on:
        - db

    pg_admin:
      image: thajeztah/pgadmin4
      ports:
        - "5050:5050"

  networks:
    roof:
      driver: bridge
