  version: '3'
  services:
    db:
      image: postgres
      ports:
        - "5555:5432"
      volumes:
        - 'postgres_data:/var/lib/postgresql/data'
        - './local:/root'
      restart: always
      networks:
        - roof

    web:
      build: .
      volumes:
        - .:/production
      ports:
        - "3000:3000"
      restart: always
      labels:
        traefik.enabled: 'true'
        traefik.port: "3000"
        traefik.docker.network: "roof"
      networks:
        - roof
      stdin_open: true
      tty: true
      depends_on:
        - lb
        - db

    lb:
      image: traefik:1.5.4-alpine
      ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
      networks:
        - roof
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml

    pg_admin:
      image: thajeztah/pgadmin4
      ports:
        - "5050:5050"
      networks:
        - roof

  volumes:
    postgres_data:

  networks:
    roof:
      driver: bridge
