default: &default
  adapter: postgresql
  host: db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mana_roof_api_development

test:
  <<: *default
  database: mana_roof_api_test

production:
  <<: *default
  database: mana_roof_api_production
  username: mana_roof_api
  password: <%= ENV['MANA_ROOF_API_DATABASE_PASSWORD'] %>
